name: flutter_themer
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  hexcolor: ^3.0.1

  provider: ^6.0.2
  path_provider: ^2.0.11
  flutter_colorpicker: ^1.0.3
  logger: ^1.1.0
  flutter_html: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/theme.json
    - assets/theme_configuration.json
    - assets/theme_generated.html
    - assets/images/iphone_14.png

